# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-88e636db-71f2-4add-bc92-28f82f402cc0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-88e636db-71f2-4add-bc92-28f82f402cc0".device = "/dev/disk/by-uuid/88e636db-71f2-4add-bc92-28f82f402cc0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/35AD-B7F3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ce80ab1b-2355-4197-ac8a-7ccfcafcf2e4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
