name: Cave-Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-stones:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Cave
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Build Fire (Nix)
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Magic Eye (nix flake check)
        run: nix flake check
      - name: Stone Linter (statix)
        run: nix run nixpkgs#statix -- check .
